name: Build and Test WPF App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install .NET Framework Developer Pack for 4.8 (usually preinstalled on windows-latest)
    # If you ever target other .NET Framework versions, you can add installation steps here.

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # This is mainly for SDK commands; your WPF app targets .NET Framework

    - name: Restore Dependencies
      run: nuget restore CyberSecurityBotGUI.sln

    - name: Check Code Formatting (optional)
      run: dotnet format --verify-no-changes
      continue-on-error: true

    - name: Build Project (Release)
      run: msbuild CyberSecurityBotGUI.sln /p:Configuration=Release /m

    - name: Run Syntax Check / Compilation Test
      run: msbuild CyberSecurityBotGUI.sln /p:Configuration=Release /warnaserror
